### PR TITLE
New test praneeth

### PR DESCRIPTION
**Pull request by Praneethg23**
Fixes and Changes in Functionalities

### CODE REVIEW

**Comment by Sharatt-Seenivasan** [comment]
Duplicate answer choices:
image

**Comment by Praneethg23** [comment]
> Duplicate answer choices: image

got it working on it

Try it now ,I fixed it

**Comment by Sharatt-Seenivasan** [comment]
Also got the following error when trying to run `npm start`:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'hbs' imported from C:\Users\shara\OneDrive\Desktop\College\CS546\cs546_final_project\data\users.js
    at new NodeError (node:internal/errors:400:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
Fixed it by commenting out `import async from "hbs/lib/async.js";` in `data/users.js`. I don't think this should cause any issues because my IDE tells me it wasn't being used. 
Yeah actually it is unsed package i guess

**Comment by Sharatt-Seenivasan** [comment]
> Also got the following error when trying to run `npm start`:
> 
> ```
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'hbs' imported from C:\Users\shara\OneDrive\Desktop\College\CS546\cs546_final_project\data\users.js
>     at new NodeError (node:internal/errors:400:5)
>     at packageResolve (node:internal/modules/esm/resolve:889:9)
>     at moduleResolve (node:internal/modules/esm/resolve:938:20)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
>     at link (node:internal/modules/esm/module_job:76:36) {
>   code: 'ERR_MODULE_NOT_FOUND'
> }
> ```
> 
> Fixed it by commenting out `import async from "hbs/lib/async.js";` in `data/users.js`. I don't think this should cause any issues because my IDE tells me it wasn't being used.

I pushed the fix to this branch.

**Comment by Sharatt-Seenivasan** [comment]
When a user gets a negative score, their current high score isn't displayed on the game result page.
image

Okay actually i made it only to display when highscore changes, fixed it now

**Comment by Sharatt-Seenivasan** [comment]
Not a bug, but the user id is printed to the console:
image

**Comment by Sharatt-Seenivasan** [comment]
> > Duplicate answer choices: image
> 
> got it working on it
> 
> Try it now ,I fixed it

Tested it multiple times, and I haven't encountered the issue again.

**Comment by Praneethg23** [comment]
> Not a bug, but the user id is printed to the console: image

i will clear that ,actually made it for debugging a issue

**Comment by Praneethg23** [comment]
> 

Ya i made options array to have unique values.

**Comment by Praneethg23** [comment]
> When a user gets a negative score, their current high score isn't displayed on the game result page. image
> 
> Okay actually i made it only to display when highscore changes, fixed it now

But will post in a while with new seed file

**Comment by Sharatt-Seenivasan** [comment]
Just fixed a bug unrelated to the stuff that you were working on. Figured I might as well quickly fix it just so I don't forget.

**Comment by Sharatt-Seenivasan** [comment]
High score still isn't displayed if a user gets a negative score:
image

Fixed this issue.

**Comment by Sharatt-Seenivasan** [comment]
Logged-in users that have not set their location are still able to access the "Local" quiz. 

Fixed this issue.

image

**Comment by Sharatt-Seenivasan** [comment]
Bird image occasionally isn't displayed in the game. 

image

**Comment by Sharatt-Seenivasan** [comment]
I created a user and set their location to Sydney, Australia. After this, I attempted to access the Local quiz. I was denied from accessing the quiz (which is exactly what should happen), but the error message I got was a little bit strange:
image

Just fixed this issue.

**Comment by Praneethg23** [comment]
> I created a user and set their location to Sydney, Australia. After this, I attempted to access the Local quiz. I was denied from accessing the quiz (which is exactly what should happen), but the error message I got was a little bit strange: image
> 
> Just fixed this issue.

My bad,I used wrong reference.

**Review by Sharatt-Seenivasan — APPROVED** [review]

**Pull request merged**
