### PR TITLE
Praneeth gubba

### PR DESCRIPTION
**Pull request by Praneethg23**
-Points Deduction for wrong answers based on the quiz(high for local to low for global)
-Points Addition based on the quiz type.
-Added options for user select quiz type of global, local and country

### CODE REVIEW

**Comment by Praneethg23** [comment]
Few more fixes for gameplay and questions db functions

**Comment by Sharatt-Seenivasan** [comment]
We can't use scientific names for the answer choices in the quiz, we have to use common names.

image

**Comment by Sharatt-Seenivasan** [comment]
Not sure how this is implemented, but birds that are 30-60ish miles away from a user's location should be considered as "local" birds and be included in the local quiz. 

image

**Comment by Sharatt-Seenivasan** [comment]
The score should be an integer instead of a long decimal. 

image

**Comment by Sharatt-Seenivasan** [comment]
Only the subject of decimals and integers, I'm not sure if I'm a fan of the score being increased/decreased by -0.5

**Comment by Sharatt-Seenivasan** [comment]
Also, it seems that score doesn't get updated properly? I got a score of 42, but it still says 7.86 on the leaderboard.

**Pull request closed without merging**
